baseURL                = "https://timchengmj.github.io/blog/"
locale                 = "zh-cn"
title                  = "Tim's Lab"
defaultContentLanguage = "zh"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"

[pagination]
    pagerSize = 10

[permalinks]
    posts = "/posts/:slug/"
    page = "/:slug/"
