[[main]]
    identifier = "posts"
    name       = "文章"
    url        = "/posts/"
    weight     = 1

[[main]]
    identifier = "projects"
    name       = "项目"
    url        = "/projects/"
    weight     = 2

[[main]]
    identifier = "archives"
    name       = "归档"
    url        = "/archives/"
    weight     = 3

[[main]]
    identifier = "search"
    name       = "搜索"
    url        = "/search/"
    weight     = 4

[[main]]
    identifier = "about"
    name       = "关于"
    url        = "/about/"
    weight     = 5

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/TimChengMJ"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "email"
    name       = "Email"
    url        = "mailto:734398377@qq.com"
    [social.params]
        icon = "messages"
